services:
  db:
    image: mysql:8.1
    container_name: savemi-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-savemi}
      MYSQL_USER: ${MYSQL_USER:-savemi_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-savemi_pass}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_backups:/backups
    networks:
      - savemi-network
    entrypoint: |
      sh -c '
      while true; do
        TIMESTAMP=$$(date +"%Y%m%d%H%M%S")
        echo "Backing up database..."
        mysqldump -h localhost -u "$$MYSQL_USER" -p"$$MYSQL_PASSWORD" "$$MYSQL_DATABASE" | gzip >/backups/savemi-$$TIMESTAMP.sql.gz
        echo "Backup done: /backups/savemi-$$TIMESTAMP.sql.gz"
        sleep 1000
      done &
      exec docker-entrypoint.sh mysqld
      '

  api:
    image: miguelferreiraa/savemi-be:${TAG:-latest}
    container_name: savemi-api
    restart: unless-stopped
    secrets:
      - jwt_private_key
      - jwt_public_key
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-db}
      SPRING_PROFILES_ACTIVE: ${API_PROFILE:-prod}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:-savemi}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-savemi_user}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-savemi_pass}
      APP_COOKIE_DOMAIN: ${APP_DOMAIN:-localhost}
      JWT_PRIVATE_KEY: file:/run/secrets/jwt_private_key
      JWT_PUBLIC_KEY: file:/run/secrets/jwt_public_key
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    networks:
      - savemi-network
    depends_on:
      - db

  frontend:
    image: miguelferreiraa/savemi-fe:${TAG:-latest}
    container_name: savemi-frontend
    restart: unless-stopped
    environment:
      FRONTEND_PROFILE: ${FRONTEND_PROFILE:-production}
      API_BASE_URL: http://localhost:8080
    networks:
      - savemi-network
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: savemi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - savemi-network

secrets:
  jwt_private_key:
    file: ./secrets/rsa.private.key
  jwt_public_key:
    file: ./secrets/rsa.public.key

volumes:
  db_data:
networks:
  savemi-network:
    driver: bridge
